name: Update Commit Hash

on:
  push:
    branches:
      - main

  # 允许从 Actions 选项卡手动运行
  workflow_dispatch:

jobs:
  create-version-file:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Get the latest commit hash
        id: get_commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create hash file
        run: |
          echo "COMMIT_HASH = \"${{ env.COMMIT_HASH }}\"" > module_name/commit_hash.py

      - name: Commit and push hash file
        run: |
          git config user.name "lovemilk2333"
          git config user.email "${{ secrets.LOVEMILK2333_EMAIL }}"
          git add -f module_name/commit_hash.py  # 忽略 .gitignore 中的规则强制添加
          git commit -m "[Action] auto update commit hash file"
          git push
